### PR TITLE
Add basic continuous integration

### PR DESCRIPTION
**Pull request by hellais**
This allows us to have some basic continuous integration for the Android app.

@xanscale @lorenzoPrimi  can you look to see why the `./gradlew clean build` is showing a lint error?

### CODE REVIEW

**Comment by bassosimone** [comment]
I think you should target the `dev` branch rather than `master`.

**Comment by xanscale** [comment]
i think is better to consider this pull request after release 2.0

**Comment by xanscale** [comment]
@lorenzoPrimi i don't know anything about travis :D

**Comment by lorenzoPrimi** [comment]
@bassosimone can you review this and merge it?

**Comment by xanscale** [comment]
merge that in branch test/instrumented

**Pull request closed without merging**
