### PR TITLE
Dependency injection configuration

### PR DESCRIPTION
**Pull request by Filmaluco**
The following PR contains the base files and configuration to install the [Dagger](https://dagger.dev/) compile-time dependency injection framework.

The refactor to include DI in most class's would be huge, since we will be refactoring the [domain logic](https://github.com/ooni/probe/issues/1448) we decided to make those changes incremental for an easier review and safer update.

Small changes can be found already in the _Application.java_ and _PreferenceManager_ class's as well as in the unit test's.

For more information and the official documentation please consult: https://dagger.dev/dev-guide/

### CODE REVIEW

**Comment by Filmaluco** [comment]
This PR also closes: https://github.com/ooni/probe/issues/1446

**Comment by lorenzoPrimi** [comment]
@Filmaluco the code looks great but I don't really understand the dependency injector. Can you explain me why is preferable to use it comparing to the current codebase? Thank you

**Comment by Filmaluco** [comment]
@lorenzoPrimi There are various advantages on using a dependency injector framework, but the most fundamentals ones are to more easily inject in test environments and allow and more structured and scalable codebase.

As we move from UITests to the refactoring UseCases and testing them this and other changes will become more obvious a quick example would be the application context, the current codebase tends to pass this argument from method to method.

_example: Function A does not need context but requires it to pass to Function B_

Dagger will allow to more easily inject the context on the Class that needs it (to Function B) and we can simplify both the call on function A and more easily test Class B.

For instance API calls, when testing we don't want to make real calls to an API.  _ApplicationModule_ provides the real api caller while _TestAppModule_ can provide a mock version where we control the return of every method call. 
Removing the need of and having to setup a state with previous instruction to test something and allowing a more convenient cleaner way to provide the test class.

**Review by bassosimone — APPROVED** [review]
This is great, thank you!

**Pull request merged**
