### PR TITLE
Fix: The modal warning about a VPN being enabled is not blocking on the test cards

### PR DESCRIPTION
**Pull request by aanorbel**
Fixes ooni/probe#1982

## Proposed Changes

  - Check If VPN is enabled before launching service and prompt user to change VPN settings before proceeding.
  - Modify test runner caller to only trigger actions to `ProgressFragment` or `exit` only when tests have actually been run.

| Light Mode | Dark Mode |
| ------------- | ------------- |
| Screenshot_20220204_134307 |  Screenshot_20220204_134240 |

### CODE REVIEW

**Comment by aanorbel** [comment]
## VPN Modal preview on various screens
| . | . |
| ------------- | ------------- |
| image  | image  |

**Comment by hellais** [comment]
This looks great!

A question and a comment:
* The order of the buttons should be inverted. The primary button (the one on the right) should be "Disable VPN" and the secondary (the one on the left) should be "Run anyways"
* What happens when you tap on Disable VPN? Do we have a way to sending the user to the Android VPN settings?

**Comment by aanorbel** [comment]
> This looks great!
> 
> A question and a comment:
> 
> * The order of the buttons should be inverted. The primary button (the one on the right) should be "Disable VPN" and the secondary (the one on the left) should be "Run anyways"
> * What happens when you tap on Disable VPN? Do we have a way to sending the user to the Android VPN settings?

User is taken to VPN settings once they tap on `Disable VPN`.

**Comment by aanorbel** [comment]
https://user-images.githubusercontent.com/17911892/152343745-fc491bed-778f-405f-93b2-df6d83d25369.mp4

Screenshot_20220203_132240

**Review by bassosimone — APPROVED** [review]
🐳 🥪 💯

**Review by bassosimone — APPROVED** [review]
Thanks!

**Comment by hellais** [comment]
It looks like the labels for the buttons in the modal are not visible when a light theme is enabled:
Screenshot 2022-02-04 at 12 06 25

They are visible when a dark theme is on:
Screenshot 2022-02-04 at 12 07 15

**Comment by aanorbel** [comment]
I didnt notice this. Let me check it out.

**Comment by aanorbel** [comment]
### Dialog styling updated

| Light Mode | Dark Mode |
| ------------- | ------------- |
| Screenshot_20220204_134307 |  Screenshot_20220204_134240 |

**Review by hellais — APPROVED** [review]
LGTM

**Pull request merged**
