### PR TITLE
fix crash for website re-run

### PR DESCRIPTION
**Pull request by aanorbel**
Fixes https://github.com/ooni/probe/issues/2043

## Proposed Changes

  - Wrap access to `RunTestService` with null check

### CODE REVIEW

**Review by bassosimone — CHANGES_REQUESTED** [review]
This diff looks good and intuitive to me: because the service may have become `null` in the meanwhile, we're not using it. I think, however, I may require some clarification on the sequence of events before signing off these changes.

Specifically, I am a bit confused at this time about what the `PRG` event does. I think this is because `PRG` is a very cryptic acronym, so I cannot recall on top of my head what it is.

My second doubt, instead, is how are we going to re-run the test if we don't have a service that we can call?

Thank you!

**Comment by aanorbel** [comment]
Hi @bassosimone , the service is only available after `TestRunBroadRequestReceiver.onServiceConnected` is called. This means the `BroadcastReceiver` can publish a progress when the `ServiceConnection` has not been establised.

**Comment by bassosimone** [comment]
@aanorbel thanks! It has now finally occurred to me that `PRG` is progress! (Can we perhaps rename these defines in a better way so that it's more obvious what they refer to?)

**Review by bassosimone — APPROVED** [review]
Everything is clear now after your explanation, thanks a lot!

LGTM 🐳

**Pull request merged**
